spring.application.name=session11

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=vietanh2k5

#cau hinh sql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.ra.edu.service=TRACE

# C?u hình ???ng d?n và tên file log
logging.file.name=logs/patient_web_service.log

# C?u hình kích th??c t?i ?a cho m?i file log
logging.logback.rollingpolicy.max-file-size=2MB

# C?u hình s? ngày l?u tr? t?i ?a (7 ngày)
logging.logback.rollingpolicy.max-history=7

# C?u hình ??nh d?ng tên file khi xoay vòng và nén (.gz)
logging.logback.rollingpolicy.file-name-pattern=logs/patient_web_service-%d{yyyy-MM-dd}.%i.log.gz

